### ISSUE TITLE
Sign In rendering outside of Side bar (Chrome, IE, FF, Android)

### ISSUE THREAD

**Issue by elachlan** [emilevictor/QR-ScanTrak-rb#2]
In Internet Explorer, Chrome and The built in browser on Samsung Galaxy S2 the rendering of the sign in form shows outside of the side menu bar.

**Comment by emilevictor** [comment]
Is this on windows?

**Comment by elachlan** [comment]
For IE, Chrome and FF Yes. For Android no.

**Comment by elachlan** [comment]
Change the input size attribute to 25 and it should fit.

input type="text" size="25" name="user[email]" id="user_email"
input type="password" size="25" name="user[password]" id="user_password"
